#!/usr/bin/env python3
"""Generate src/dalec_jax/indices.py from the DALEC_1100 C source.

The C source is the authoritative description of executable behaviour, so
indices and parameter bounds are parsed straight out of
DALEC_<id>_INDICES.c and PARS_INFO_<id>.c and emitted as a Python module.
Hand-writing an index literal anywhere in dalec_jax is a defect (CLAUDE.md
rule 11): the earlier in-repo JAX port silently corrupted four flux slots
exactly that way.

Parsing logic vendored from cardamom_research/scripts/dalec_model_info.py
(same author); validation preserved: indices must be a contiguous 0..n-1
permutation, every parameter needs literal min < max bounds.

Usage:  python tools/gen_indices.py [--check]
  --check : regenerate to a string and diff against the committed
            indices.py; exit 1 on any difference (used by the test suite).
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

MODEL_ID = 1100
PKG = Path(__file__).resolve().parent.parent
C_MODEL_DIR = (PKG / "../../C/projects/CARDAMOM_MODELS/DALEC" / f"DALEC_{MODEL_ID}").resolve()
TARGET = PKG / "src/dalec_jax/indices.py"


def _parse_index_struct(text: str, struct_name: str) -> dict[int, str]:
    """Parse `struct <name>{ int a; int b; } <name>={0,1};`"""
    m = re.search(r"struct\s+%s\s*\{(.*?)\}\s*%s\s*=\s*\{(.*?)\}\s*;"
                  % (re.escape(struct_name), re.escape(struct_name)),
                  text, re.DOTALL)
    if not m:
        raise ValueError(f"could not find struct {struct_name}")
    body, init = m.group(1), m.group(2)
    names = re.findall(r"int\s+([A-Za-z_][A-Za-z0-9_]*)\s*;", body)
    init = re.sub(r"/\*.*?\*/", " ", init, flags=re.DOTALL)
    init = re.sub(r"//[^\n]*", " ", init)
    idx = [int(x) for x in re.findall(r"-?\d+", init)]
    if len(names) != len(idx):
        raise ValueError(f"{struct_name}: {len(names)} names but {len(idx)} indices")
    if sorted(idx) != list(range(len(idx))):
        raise ValueError(f"{struct_name}: indices not a contiguous 0..n-1 permutation")
    return dict(zip(idx, names))


def _parse_par_bounds(text: str) -> tuple[dict[str, float], dict[str, float]]:
    """Parse `parmin[P.name]=<literal>;` lines; loud failure on expressions."""
    out: dict[str, dict[str, float]] = {"parmin": {}, "parmax": {}}
    for raw in text.splitlines():
        line = raw.split("//")[0].strip()
        m = re.match(r"(parmin|parmax)\s*\[\s*P\.([A-Za-z_][A-Za-z0-9_]*)\s*\]"
                     r"\s*=\s*([^;]+);", line)
        if not m:
            continue
        which, name, expr = m.group(1), m.group(2), m.group(3).strip()
        expr = re.sub(r"/\*.*?\*/", "", expr).strip()
        try:
            out[which][name] = float(expr)
        except ValueError as exc:
            raise ValueError(f"non-literal bound {which}[{name}] = {expr!r}") from exc
    return out["parmin"], out["parmax"]


def generate() -> str:
    idx_path = C_MODEL_DIR / f"DALEC_{MODEL_ID}_INDICES.c"
    par_path = C_MODEL_DIR / f"PARS_INFO_{MODEL_ID}.c"
    idx_text = idx_path.read_text()
    par_text = par_path.read_text()

    pools = _parse_index_struct(idx_text, f"DALEC_{MODEL_ID}_POOLS")
    fluxes = _parse_index_struct(idx_text, f"DALEC_{MODEL_ID}_FLUXES")
    params = _parse_index_struct(idx_text, f"DALEC_{MODEL_ID}_PARAMETERS")
    edcs = _parse_index_struct(idx_text, f"DALEC_{MODEL_ID}_EDCs")
    parmin, parmax = _parse_par_bounds(par_text)

    missing = (set(params.values()) - set(parmin)) | (set(params.values()) - set(parmax))
    if missing:
        raise ValueError(f"parameters without bounds: {sorted(missing)}")
    for name in params.values():
        if not parmin[name] < parmax[name]:
            raise ValueError(f"bad bounds for {name}: {parmin[name]!r} !< {parmax[name]!r}")

    sha_idx = hashlib.sha256(idx_text.encode()).hexdigest()
    sha_par = hashlib.sha256(par_text.encode()).hexdigest()

    def cls(name: str, mapping: dict[int, str], c_struct: str) -> str:
        lines = [f"class {name}:", f'    """C struct {c_struct} (index constants)."""']
        for i in sorted(mapping):
            lines.append(f"    {mapping[i]} = {i}")
        return "\n".join(lines)

    def tup(name: str, mapping: dict[int, str]) -> str:
        items = ", ".join(f'"{mapping[i]}"' for i in sorted(mapping))
        return f"{name} = ({items})"

    def ftup(name: str, values: list[float]) -> str:
        items = ", ".join(repr(v) for v in values)
        return f"{name} = ({items})"

    ordered = [params[i] for i in sorted(params)]
    parts = [
        '"""GENERATED by tools/gen_indices.py -- DO NOT EDIT.',
        "",
        f"Source of truth: DALEC_{MODEL_ID}_INDICES.c / PARS_INFO_{MODEL_ID}.c.",
        f"sha256(DALEC_{MODEL_ID}_INDICES.c) = {sha_idx}",
        f"sha256(PARS_INFO_{MODEL_ID}.c)     = {sha_par}",
        '"""',
        "",
        f"MODEL_ID = {MODEL_ID}",
        f"NOPOOLS = {len(pools)}",
        f"NOFLUXES = {len(fluxes)}",
        f"NOPARS = {len(params)}",
        f"NOEDCS = {len(edcs)}",
        "",
        cls("P", params, f"DALEC_{MODEL_ID}_PARAMETERS"),
        "",
        cls("F", fluxes, f"DALEC_{MODEL_ID}_FLUXES"),
        "",
        cls("S", pools, f"DALEC_{MODEL_ID}_POOLS"),
        "",
        cls("E", edcs, f"DALEC_{MODEL_ID}_EDCs"),
        "",
        tup("PAR_NAMES", params),
        tup("FLUX_NAMES", fluxes),
        tup("POOL_NAMES", pools),
        tup("EDC_NAMES", edcs),
        "",
        ftup("PARMIN", [parmin[n] for n in ordered]),
        ftup("PARMAX", [parmax[n] for n in ordered]),
        "",
    ]
    return "\n".join(parts)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="diff against committed indices.py instead of writing")
    a = ap.parse_args()
    text = generate()
    if a.check:
        current = TARGET.read_text() if TARGET.exists() else ""
        if current != text:
            sys.stderr.write("indices.py is stale or hand-edited -- rerun "
                             "tools/gen_indices.py\n")
            return 1
        print("indices.py is up to date")
        return 0
    TARGET.write_text(text)
    print(f"wrote {TARGET}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
